export const API_BASE_URL = 'https://api.themoviedb.org/3';
export const BEARER_KEY = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3MzNmNDYwNWM0OTM3NThiMWJlYmJmYTYwZWYzZjM3NiIsIm5iZiI6MTc0NDc4NzA0MC40NjQsInN1YiI6IjY3ZmY1NjYwOWQxZjc3OGFiODk5YTMwMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.JssCtHdqbrUsHAuzKboPCMifNqm1lbOmpOqHrMYeDU0';
